# RTL多智能体优化系统快速测试配置

# 实验配置
experiment:
  name: "rtl_quick_test"
  project_name: "rtl_test"
  save_dir: "./test_experiments"
  use_wandb: false

# 模型配置 - 使用较小的设置用于测试
models:
  meta_optimizer:
    model_name: "deepseek-ai/deepseek-coder-6.7b-instruct"
    max_length: 2048
    device: "auto"

  code_rewriter:
    model_name: "deepseek-ai/deepseek-coder-6.7b-instruct"
    max_length: 2048
    device: "auto"

# 训练配置 - 快速测试参数
training:
  num_epochs: 3
  episodes_per_epoch: 5
  max_steps_per_episode: 8
  batch_size: 2
  learning_rate: 1e-3
  weight_decay: 1e-5
  discount_factor: 0.9

  learning_rates:
    meta_optimizer: 1e-3
    code_rewriter: 1e-3

  ppo_mini_batch_size: 2
  ppo_epochs: 2
  clip_epsilon: 0.3

  clip_mode: "turn"
  agg_mode: "trajectory"
  max_turns: 10

# 环境配置
environment:
  max_steps: 10
  success_threshold: 0.6
  timeout_penalty: -0.05

  verification:
    enable_verilator: true
    enable_yosys: false  # 关闭较慢的综合检查
    enable_iverilog: true
    syntax_weight: 0.6
    synthesis_weight: 0.0
    compilation_weight: 0.4

# 数据配置 - 使用生成的示例数据
data:
  train_data_path: null  # 将使用生成的示例数据
  test_data_path: null
  max_prompt_length: 2048
  max_response_length: 1024
  augment_data: false
  train_test_split: 0.8
  generate_sample_data: true
  num_sample_cases: 10

# 评估配置
evaluation:
  eval_freq: 1  # 每个epoch都评估
  eval_episodes: 3
  save_best_model: true

# 日志配置
logging:
  level: "DEBUG"
  save_freq: 2
  log_file: "./logs/quick_test.log"

  wandb:
    entity: null
    tags: ["rtl", "test", "quick"]
    notes: "快速测试配置"

# 硬件配置
hardware:
  device: "auto"
  mixed_precision: false  # 关闭混合精度以简化调试
  gradient_checkpointing: false
  max_memory_gb: 8

# 调试配置
debug:
  enable_debug_mode: true
  save_intermediate_codes: true
  verbose_logging: true
  profile_performance: false